### ISSUE TITLE
[BUG] Template PrimeMU 

### ISSUE THREAD

**Issue by clarkmedina** [pulseP1986/free-mu-cms-templates#3]
Account Panel shows this error

Call to a member function userdata() on null

Character Info not showing the class icon and the character inventory BG
![image](https://github.com/pulseP1986/free-mu-cms-templates/assets/40266456/176a42dd-d59a-41b6-afc3-dbeebe093f83)

**Comment by pulseP1986** [comment]
This template is very poor coded and i don't plan to do bug fixes on it.
